from zincbase import KB

# predicates
isA = 'isA'
extends = 'extends'
licenseOf = 'licenseOf'
authorOf = 'authorOf'
copyrightHolderOf = 'copyrightHolderOf'
extendsConditions = 'extendsConditions'
extendsRights = 'extendsRights'
extendsWarranties = 'extendsWarranties'
repositoryConditions = 'repositoryConditions'
repositoryRights = 'repositoryRights'
repositoryTermsConditions = 'repositoryTermsConditions'

# knowledge objects
mit_license = 'mit_license'
gnu_license = 'gnu_license'
merchantability_license = 'merchantability_license'
guarantee_license = 'guarantee_license'
right = 'right'
commercial_use = 'commercial_use'
implied_warranty = 'implied_warranty'
expressed_warranty = 'expressed_warranty'
modification_use = 'modification_use'
distribution_use = 'distribution_use'
private_use = 'private_use'
patent_use = 'patent_use'
license_notice = 'license_notice'
copyright_notice = 'copyright_notice'
state_changes = 'state_changes'
disclose_source = 'disclose_source'
same_license = 'same_license'

condition = 'condition'
warranty = 'warranty'